"""initial schema

Revision ID: 38acc3b14e80
Revises: 
Create Date: 2025-12-23 14:28:34.788266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38acc3b14e80'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the user'),
    sa.Column('email', sa.String(length=255), nullable=False, comment="User's email address (used for login)"),
    sa.Column('hashed_password', sa.String(length=255), nullable=False, comment='Bcrypt hashed password'),
    sa.Column('full_name', sa.String(length=255), nullable=False, comment="User's full name"),
    sa.Column('phone_number', sa.String(length=20), nullable=True, comment="User's contact phone number"),
    sa.Column('role', sa.String(length=50), nullable=False, comment='User role for authorization (ADMIN, OWNER, MANAGER, FLOOR_MANAGER, WORKER)'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='Account status (ACTIVE, INACTIVE, PENDING_PASSWORD_CHANGE, SUSPENDED, LOCKED)'),
    sa.Column('is_first_login', sa.Boolean(), nullable=False, comment='Flag indicating if user must change password on first login'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Timestamp when user was created'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Timestamp when user was last updated'),
    sa.Column('created_by_id', sa.UUID(), nullable=True, comment='ID of user who created this account'),
    sa.CheckConstraint("email ~* '^[A-Za-z0-9._%%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$'", name='check_valid_email_format'),
    sa.CheckConstraint("role IN ('ADMIN', 'OWNER', 'MANAGER', 'FLOOR_MANAGER', 'WORKER')", name='check_valid_role'),
    sa.CheckConstraint("status IN ('ACTIVE', 'INACTIVE', 'PENDING_PASSWORD_CHANGE', 'SUSPENDED', 'LOCKED')", name='check_valid_status'),
    sa.CheckConstraint('LENGTH(TRIM(full_name)) > 0', name='check_full_name_not_empty'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    comment='Users table storing employee and administrator information'
    )
    op.create_index('idx_users_created_at', 'users', ['created_at'], unique=False)
    op.create_index('idx_users_email_unique', 'users', ['email'], unique=True)
    op.create_index('idx_users_full_name_trgm', 'users', ['full_name'], unique=False, postgresql_using='gin', postgresql_ops={'full_name': 'gin_trgm_ops'})
    op.create_index('idx_users_role_status', 'users', ['role', 'status'], unique=False)
    op.create_index('idx_users_role_status_created', 'users', ['role', 'status', sa.literal_column('created_at DESC')], unique=False, postgresql_using='btree')
    op.create_index(op.f('ix_users_created_by_id'), 'users', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_full_name'), 'users', ['full_name'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_status'), 'users', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_status'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_full_name'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_created_by_id'), table_name='users')
    op.drop_index('idx_users_role_status_created', table_name='users', postgresql_using='btree')
    op.drop_index('idx_users_role_status', table_name='users')
    op.drop_index('idx_users_full_name_trgm', table_name='users', postgresql_using='gin', postgresql_ops={'full_name': 'gin_trgm_ops'})
    op.drop_index('idx_users_email_unique', table_name='users')
    op.drop_index('idx_users_created_at', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
